FROM python:3.10

RUN git -b issuer-kit-integration clone https://github.com/bcgov/traction.git /app

WORKDIR /app/services/endorser

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000
ENTRYPOINT ["./docker-entrypoint.sh"]